mock = true   # If true, program generate fake serial data

[[data-sinks]]
type        = "json_file"
enabled     = true
sample_period = 60
name = 'json-data'

[[data-sinks]]
type        = "csv_file"
enabled     = true
sample_period = 60
name = 'csv-data'

# [[data-sinks]]
# name='influx-test'
# type        = "influxdb"
# enabled     = true
# sample_period = 60
# url         = "https://influx.example.com:8086"
# database      = "test-rig-data"
# measurement = "rig_metrics_v2"

[mass]
units = "g"

[mass.serial]
port = "/dev/ttyACM0"            # Scale serial port (e.g., COM10)
baudrate = 2400
bytesize = 7
parity = 'E'

[alicat-shared.serial]           # one port for all Alicats
port = "/dev/ttyUSB0"
baudrate = 19200
timeout = 0.5

[flow]
full-scale-min = 0.0
full-scale-max = 20.0
unit-id = "A"
flow-unit = "SLPM"
# no serial uses alicat-shared

[high-dp]
full-scale-min = 0.0
full-scale-max = 10.0
unit-id = "B"
pressure-unit = "PSI"
# no serial shared

[low-dp]
full-scale-min = 0.0
full-scale-max = 2.0
unit-id = "C"
pressure-unit = "inH2O"
# no serial shared
